version: 2.1

jobs:
  checkout_and_unit_test:
    machine: true
    steps:
      - checkout
      - run: echo "checkout and unit tests completed!"
  deploy_backend:
    machine: true
    steps:
      - checkout
      - run: echo "backend deployed!"
  integration_tests_backend:
    machine: true
    steps:
      - checkout
      - run: echo "integration tests for the backend are completed!"
  deploy_staging:
    machine: true
    steps:
      - checkout
      - run: echo "staging deploy done!"
  acceptance_test_1:
    machine: true
    steps:
      - checkout
      - run: echo "acceptance test 1 completed!"
  acceptance_test_2:
    machine: true
    steps:
      - checkout
      - run: echo "acceptance test 2 completed!"
  acceptance_test_3:
    machine: true
    steps:
      - checkout
      - run: echo "acceptance test 3 completed!"
  acceptance_test_4:
    machine: true
    steps:
      - checkout
      - run: echo "acceptance test 4 completed!"
  deploy_production:
    machine: true
    steps:
      - checkout
      - run: echo "succesfully deployed to production!"
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_test_1:
          requires:
            - deploy_staging
      - acceptance_test_2:
          requires:
            - deploy_staging
      - acceptance_test_3:
          requires:
            - deploy_staging
      - acceptance_test_4:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - acceptance_test_1
            - acceptance_test_2
            - acceptance_test_3
            - acceptance_test_4

